services:
  front-end-gradio:
    container_name: front-end-gradio
    build:
      context: ./modules/front-end-gradio
    ports:
      - "9001:7860"
    volumes:
      - ./modules/front-end-gradio/src:/src
      - ./modules/front-end-gradio/data:/data
    env_file:
      - setup.env
      - ./modules/front-end-gradio/config.env
    depends_on:
      - redis
      - knowledge-demo